version: '3.6'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - "./database:/var/lib/mysql"
  db_pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root
      PMA_PASSWORD: root
  www:
    image: php:apache-espe
    depends_on:
    - db
    volumes:
    - "./www:/var/www/html"
    ports:
    - 8081:80
