version: '3.6'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - "./database:/var/lib/mysql"
  db_pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_HOST: mysql
  www:
    image: php:apache-espe
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
    depends_on:
    - db
    volumes:
    - "./www:/var/www/html"
    #- "./logs:/usr/local/etc/php/php.ini"
    ports:
    - 8081:80
